### ISSUE TITLE
Add filter for WhatsApp & Facebook Messenger tests

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-explorer#101]
Currently when filtering measurements (via OONI Explorer) per test, the new WhatsApp and Facebook Messenger tests don't appear as options in the filter drop-down menu. 

It would be extremely useful to be able to filter measurements based on these tests, especially since these apps are being blocked in various countries lately (and users will want to be able to get quick access to those measurements).

**Comment by hellais** [comment]
This is implemented.
