### ISSUE TITLE
Fix Test Name Filter

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-explorer#123]
There seems to be a bug that prevents the filtering of measurements based on tests. 

Below is an example:

1. I go to the Cameroon country page: https://explorer.ooni.torproject.org/country/CM
2. I click on "Filter Results"
3. I select "Facebook Messenger" in the Test Name drop down menu
4. I click "Apply Filter"

I expect to only see Facebook Messenger measurements below. Instead, I just see the normal measurements that were already there, with no difference.

I keep clicking "Apply Filter" and keep waiting.... but nothing happens.

This seems to also be an issue across other OONI Explorer country pages.

**Comment by hellais** [comment]
This is fixed.
