### ISSUE TITLE
 404 - Report Not Found

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-explorer#131]
The following report produced a 404 on the current version of OONI explorer:
https://api.ooni.io/api/v1/measurement/temp-id-246411968

https://explorer.ooni.io/measurement/20181120T092944Z_AS199335_6V7Di7t3qUP7qVBYDlOHo9nxgle5NMQIDGHV50wtmCLuZTVPzU?input=http:%2F%2Fmp3.com%2F

**Comment by hellais** [comment]
When I access the page you linked to I do see a measurement.

**Comment by anadahz** [comment]
I recall a 404 but maybe I'm mistaken or it was a transient error.
Will reopen if it ever occurs.
