### ISSUE TITLE
Add support for choosing a date range

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#14]
It should be possible from the views that show the list of measurements to select a range for which to search for measurements.

The most basic implementation can just be something where you choose a start date and end date, but ideally it would be something prettier such as a timeline where you can brush the beginning and end (similar to the date selector here: http://square.github.io/crossfilter/)

cc @simonv3

**Comment by simonv3** [comment]
So some thoughts: 

* [ ] When clicking on a bar in the view-country tab it'd be nice if the measurements below were filtered by that.
* [ ] An actual date range picker for angular would be a good input field for now

I'm not sure whether our data updates fast enough for crossfilter to work very quickly, but I can investigate what would need to happen for it.

**Comment by hellais** [comment]
This is implemented as MVP
