### ISSUE TITLE
Improve country level view

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#18]
The country level should provide the following charts, visual elements:

* [x] A bar chart that shows number of sites blocked per number of sites tested. Every bar shall be a certain date and it should be split into two (bottom part is number of blocked site, total height should be number of sites tested)

* [x] A listing of all the sites that have been identified as being blocked in a given country with it's category.

* [x] A section that shows what are the reasons for censorship (DNS, TCP blocking, HTTP proxy)

* [x] A section with the vendor(s) that were identified in the given country.

When no data is available for the given country (we can accurately implement the first heuristic only for 2 countries) it should display no data available.

There should also be a way to pivot around the ASN (network/ISP) from where the measurements were run.

@simonv3

**Comment by simonv3** [comment]
Hey @hellais, I just wanted to verify whether this is what you had in mind for the bar chart:
![screenshot 2016-01-06 14 03 54](https://cloud.githubusercontent.com/assets/485583/12156237/9d1ae6ec-b47e-11e5-9a3f-32f6f46794c1.png)

**Comment by hellais** [comment]
Yes that is exactly what I had in mind. I am working on implementing this in the data pipeline so that I can expose that data for you. Note that currently we have accurate blockpage detection only for 2-3 countries, so this would only appear in those cases.

**Comment by simonv3** [comment]
Just going to put this link to the queries Hellias built for the 2 countries here: https://gist.github.com/hellais/712085ded94379319073#file-queries-sql-L19

**Comment by hellais** [comment]
@simonv3 I created a materialised view for the blockpage counts and implemented the relative ooni-api side endpoint to access it here: https://github.com/TheTorProject/ooni-api/commit/8b5c381a599904aef0ae95f7f40816d807b874ac

**Comment by hellais** [comment]
I implemented the list of vendors and the list of blocked websites here: https://github.com/TheTorProject/ooni-api/commit/4c6590f9bc15549ef1fa191167c3c1c60421580e

**Comment by simonv3** [comment]
Alright, I've got a pretty rough v1 for the 1st thing:

![screenshot 2016-01-14 13 58 16](https://cloud.githubusercontent.com/assets/485583/12338896/03edc148-bac7-11e5-8a44-7a7129172399.png)

**Comment by simonv3** [comment]
Tackled just a list for the second bullet in https://github.com/simonv3/ooni-api/commit/24f8e71f7334311332820db493363aca65ae1082

**Comment by simonv3** [comment]
I've added a section that just lists vendors in https://github.com/simonv3/ooni-api/commit/b257b5a1ec4e38209bc481937bfa68dfbaeff337, but going to need a little bit of direction on how to display methods of censorship. I'll ping you tomorrow @hellais.

**Comment by hellais** [comment]
Regarding the list of websites identified as being blocked it would be nice if they could be clustered by date in which the measurement is run, since just listing them all in the page leads to a lot of them being duplicated and it's not clear why they are being presented twice.

**Comment by simonv3** [comment]
Sounds good.

**Comment by simonv3** [comment]
This is a bit more organized view: 

![screenshot 2016-01-20 18 06 11](https://cloud.githubusercontent.com/assets/485583/12469443/9c2445a8-bfa0-11e5-9e6c-5ed77d0edb42.png)
