### ISSUE TITLE
Sometimes clicking on the map doesn't work, or takes a long time to give visual feedback. 

### ISSUE THREAD

**Issue by simonv3** [TheTorProject/ooni-explorer#24]

**Comment by simonv3** [comment]
Hey @hellais, I definitely remember this being an issue occasionally, but I'm having a bit of an issue reproducing it. I added some log + timestamps to the printout, and have been trying to keep an eye on when this happens. Let me know if you're noticing where abouts in the control flow it does thanks to the timers. Maybe it's another DOM load delay, so maybe we need to be a bit more liberal with in-view?

**Comment by hellais** [comment]
I am also having problems reproducing it in an accurate way. What I noticed is that when it happens, as soon as I open the developer console the map registers the click event and performs the redirect, so I am not really sure how is best to debug it.

**Comment by hellais** [comment]
It seems like the issue is related to the `$location.path()` statement not being executed properly. This could perhaps be a fix to the problem: http://stackoverflow.com/a/11932283.

**Comment by simonv3** [comment]
Oh so maybe it's because it's outside of the regular angular processing and it just waits till the next render? I'll investigate.

**Comment by simonv3** [comment]
I've added $scope.$apply to the click function in c7814ea.

**Comment by hellais** [comment]
I believe this has now been resolved since I haven't seen it anymore in recent versions of it.
