### ISSUE TITLE
Design and implement interface for "Highlights"  page

### ISSUE THREAD

**Issue by bnvk** [TheTorProject/ooni-explorer#28]
Currently, the highlights page is a bit under developed. The goal is to make it engaging and helpful to get an understanding of given countries and censorship. Some ideas towards this are:

- Two column "boxes" for each country
- Engaging title
- Brief description
- Country flag
- Link to measurements / call to action
- Timestamp / when discovery was made
- Category (blocking, tampering, correlation)

**Comment by hellais** [comment]
I stabbed out a highlights page in https://github.com/TheTorProject/ooni-explorer/commit/2cdfb7cca64049f06f5f20a350395a44681bd99a and @agrabeli added some descriptions to it.

**Comment by hellais** [comment]
The basic for this is implemented.
