### ISSUE TITLE
Refactor "Map" widget in main page

### ISSUE THREAD

**Issue by bnvk** [TheTorProject/ooni-explorer#29]
The current iteration of map is good, but can be improved with perhaps the following features / tweaks

- [x] Make map wider
- <s>Add "zoom" buttons</s>
- [ ] Do not color countries to resemble "confirmed censorship"
- <s> Make clicking on country zoom + trigger a tooltip with details + link</s>
- [ ] Replace icons with better or pin points
- [x] Change decimal (10.000) to comma (10,000) in map key
- [x] Make map legend slightly nicer

**Comment by simonv3** [comment]
With the "confirmed censorhip" do you mean the color used in the data graph?

**Comment by hellais** [comment]
@simonv3 yes that is correct. The idea would be to drop using a different color for the countries where we identified censorship (currently magenta/red) and switch to using an icon for those instances too.

**Comment by hellais** [comment]
I began implementing the zoom functionality with a tooltip like effect in this branch: https://github.com/TheTorProject/ooni-explorer/tree/feature/map-zoom, but I am not actually very satisfied with the usability of this approach. I think that for this release we should not include the zoom functionality and keep it as it is.

Thoughts?

**Comment by hellais** [comment]
Moved the remaining items to #76
