### ISSUE TITLE
Make icon for navbar of ooni-explorer

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#34]
It would be cool to have for the navbar an icon similar to the one @zlailari (and @TylerJFisher?) did for the hackthenorth-ooni-looking-glass:
https://github.com/TylerJFisher/hackthenorth-ooni-looking-glass/blob/master/static/img/ooni-looking-glass-logo.png

**Comment by simonv3** [comment]
Just quickly did some resizing of the looking glass octopus:

![ooni-looking-glass-logo-24x24](https://cloud.githubusercontent.com/assets/485583/12800850/e9826cfc-ca8c-11e5-9482-9769a6edc1a8.png) (24x24)
![ooni-looking-glass-logo-48x48](https://cloud.githubusercontent.com/assets/485583/12800853/e9a1c3e0-ca8c-11e5-9da7-78c51a2a10de.png) (48x48)
![ooni-looking-glass-logo-64x64](https://cloud.githubusercontent.com/assets/485583/12800854/e9a51bc6-ca8c-11e5-945f-e4018e166adb.png) (64x64)
![ooni-looking-glass-logo](https://cloud.githubusercontent.com/assets/485583/12800852/e996c5a8-ca8c-11e5-871b-800d8989c40a.png) (original)

I think the 48x48 size would work pretty well in the navbar. Maybe on a white circle background?

**Comment by bnvk** [comment]
@simonv3 thanks, i'm saved and added these to the repo!
