### ISSUE TITLE
Overall interface design & usability improvements

### ISSUE THREAD

**Issue by bnvk** [TheTorProject/ooni-explorer#36]
Here is a collection of various design tweaks and improvements that I plan to implement to improve upon the great work everyone has done thus far!

- [x] Tweak icon and add to topbar
- [x] Rename to "OONI Explorer"
- [x] Move "World, Explorer, Highlights" into navbar
- [x] Clear title, description of sections
- [x] Hide results table on loading

Icons that should be created / found / used throughout site are

- [x] Vendor - evidence of tampering
- [x] Tampering - unknown vendor
- [x] Confirmed - case of censorship
- [x] Normal - where measurement looks "normal"
- [x] Statistics - about a country
- [ ] Squid - censorship tool "squid proxy"
- [ ] Bluecoat - censorship tool
- [x] Measurement
- [x] HTTP Headers - of request
- [x] HTML Body - from a test

**Comment by simonv3** [comment]
I came here to create an issue along the lines of "We need to show this to someone who doesn't know what this stuff means and see how they flounder". 

I think there's a lot of stuff that's a bit overwhelming and confusing without context, so we should do a better job of explaining those things.

**Comment by simonv3** [comment]
Was doing some doodling for some of these icons:

![img_20160203_160745](https://cloud.githubusercontent.com/assets/485583/12801316/9caf6c14-ca90-11e5-98ed-0c8de1afb7bf.jpg)

**Comment by bnvk** [comment]
@simonv3 nice start on those icon sketches. Did you start turning any of them into vectors yet? If not, I can do so, or I can take over wherever you are currently at. 

Wanna commit them to the @opensourcedesign/icons repo maybe in a folder like `network-related` or something?

**Comment by simonv3** [comment]
Yeah, I was thinking of adding them to OSD. Like I told you, I haven't actually converted these to vectors yet.

**Comment by simonv3** [comment]
(I was hoping we could assign two people)

**Comment by bnvk** [comment]
My first pass at most of these icons

![ooni-icon-font](https://cloud.githubusercontent.com/assets/48677/13877505/64f6e5fc-ed0b-11e5-90f6-9a17ce69ed04.png)

I've implemented them as an icon font using [IcoMoon](https://icomoon.io/) tool!

**Comment by simonv3** [comment]
These look fantastic.

**Comment by hellais** [comment]
Moved the vendor icons to #77
