### ISSUE TITLE
Improve the wording of "input" with something more clear

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#43]
@agrabeli suggested that for the tests where we are talking about a website we use that term instead of saying "input".

To do this we should replace input with something else when the test is of the following types:

* dns_consistency
* http_requests
* http_host

**Comment by simonv3** [comment]
:+1: that definitely took me a moment to grasp when working with this initially.

**Comment by hellais** [comment]
This has been implemented.
