### ISSUE TITLE
Make the websites being tested for censorship more visible

### ISSUE THREAD

**Issue by hellais** [TheTorProject/ooni-explorer#44]
@agrabeli was highlighting the fact that the websites that have been identified as being censorship are not very visible/accessible from the country level view and we should do a better job at making it clear that if you scroll down you can find them.

A suggestion was that we make something like a table of contents at the beginning of the page that sends the user to that section of the page.

Any other ideas?

**Comment by simonv3** [comment]
Table of contents is a good idea, especially if it's in-lined well like how wikipedia does it (where the text flows around it).

Another option is to add a "Iran blocks x websites, view them" type link at the top, and then link to the websites that have been blocked. 

This also made me think - should we make websites that are measured as blocked by the most recent measurements more distinct? eg - if a measurement in 2015/01 showed a website as blocked, but that website is no longer detected as blocked in 2016/01, should we highlight that somehow?

**Comment by hellais** [comment]
This is implemented.
