### ISSUE TITLE
Incorrect country details json loaded from factbook

### ISSUE THREAD

**Issue by EmergentOrder** [TheTorProject/ooni-explorer#78]
For example, the "Nicaragua" page displays the world factbook country details for Nigeria.

It seems that there is an encoding mismatch here. From the factbook repo README:
"Note: All country profiles use the "official" two-letter GEC (formerly FIPS) codes and NOT the ISO codes (you might be used to) e.g. au for Austria (and not at), gm for Germany (and not de), and so on."

ooni-explorer appears to be using: https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

**Comment by simonv3** [comment]
Hmm, that would explain all of the mismatches @hellais has been steadily fixing. I'm not sure if there's a quick way to find all the wrong ones and convert them? I'd prefer to stick to ISO as GEC is a US Government thing. 

Here's a list comparing them, says last updated two years ago: http://www.statoids.com/wab.html

**Comment by hellais** [comment]
This should now have been fixed.
