### ISSUE TITLE
Correct country name "Viet Nam"

### ISSUE THREAD

**Issue by anadahz** [TheTorProject/ooni-explorer#86]
Country's name [Viet Nam](https://explorer.ooni.torproject.org/country/VN) should be corrected to Vietnam.

**Comment by hellais** [comment]
It can be spelled either "Vietnam" or "Viet Nam". The vietnamese spelling of the country is Việt Nam, so english if you drop the diacritics you get "Viet Nam" and dropping also the space leads to "Vietnam", but both are correct.

Also note that we take the names of countries from the CIA factbook data and that is how it's spelled in there.

**Comment by anadahz** [comment]
FYI, CIA factbook [lists](https://www.cia.gov/library/publications/the-world-factbook/geos/vm.html) (VN) as Vietnam.

**Comment by hellais** [comment]
My bad, we actually pull in the country names from this data source: https://github.com/OpenBookPrices/country-data.
