### ISSUE TITLE
Filtering: List countries alphabetically in drop-down menu

### ISSUE THREAD

**Issue by agrabeli** [TheTorProject/ooni-explorer#98]
I am referring to the "Explorer" section of OONI Explorer, where users can filter the results directly based on country code, test input, test name, etc.

The drop-down menu bar of "Country code" has the countries randomly listed, and not alphabetically. This makes it a bit harder/time-consuming to search for a country. It would be nice if countries were listed alphabetically here. :)

Also, given that the country codes are not listed, but rather the country names, I would suggest changing "Country code" to "Country".

**Comment by hellais** [comment]
This is done
